### ISSUE TITLE
Initial start up of global.R

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#15]
You have 

```
packagesloaded <-
  c("tidyverse",
    "here",
    "deSolve",
    "shiny",
    "shinyhelper",
    "shinyjs",
    "shinyvalidate",
    "shinyWidgets") |>
  lapply(FUN = require, character.only = TRUE) |>
  as.logical() |>
  all()
```

1) Is there a reason why _ggplot2_ library is not on the list?

2) Also I am trying to deploy this to ShinyApps.io with a single click on my IDE but the deployed version (https://spatialepisim.shinyapps.io/episim/) always crashes with this message on the browser

<img width="322" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/66414e65-8cf4-4927-b17a-70d5b83dfd8a">

Here a screenshot of the LOGS

<img width="695" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/1e5a68a8-dc1c-4e79-b4a6-71017b2a50bc">

Any suggestions to fix it?

**Comment by bryce-carson** [comment]
1. ggplot2 is automatically loaded by loading the tidyverse metapackage.
2. Please pull the latest code before deploying: I have fixed the issue where `exit` was called when I meant to call `quit`.
3. Install the package `shinyWidgets` on your local machine, if it is not already installed.
4. Please also install the `here` package, if it is not already installed.

[According to the _introductory_ documentation for the `rsconnect` ("RStudio Connect") package](https://docs.posit.co/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud), documenting deployment to the [shinyapps.io](https://shinyapps.io) cloud service, clicking the _Publish_ button to deploy the application causes a couple functions from the renv package to be called. To be clear, pushing the button starts a process beginning with the rsconnect package.

From the trail of documentation the rsconnect led me on, the appDependencies function uses an algorithm to detect application dependencies which are installed in an Ubuntu virtual machine which shinyapps.io uses to run your application. The first option is the one I'll recommend to resolve the issue.

> Dependency discovery:
> 
>      rsconnect use one of three mechanisms to find which packages your
>      application uses:
> 
>        1. If ‘renv.lock’ is present, it will use the versions and
>           sources defined in that file. If you're using the lockfile
>           for some other purpose and don't want it to affect
>           deployment, add ‘renv.lock’ to ‘.rscignore’.

5. Please interactively load the renv library, if not already loaded.
6. Run the following code to create the needed lock file with the proper dependencies.
    ```r
    renv::init()
    renv::install(
    c("tidyverse", 
    "here", 
    "deSolve", 
    "shinyhelper", 
    "shinyjs", 
    "shinyvalidate", 
    "shinyWidgets"))
    renv::update()
    ```
7. Click _Publish_ again.

**Comment by bryce-carson** [comment]
Please close the issue if the above procedure works for you and the deployment is fixed. 😄

Please note that resetting the application is currently broken. 😢 However, many fixes for other issues have been introduced.

**Comment by ashokkrish** [comment]
I followed the instructions but the error still persists. Here is a new LOGS

<img width="689" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/e4cdda3e-7999-4a79-8f6a-11932beb6453">

**Comment by bryce-carson** [comment]
Interesting.

Can you try restarting your R session, then loading the packages using the expression in the global.R file, then calling renv::update() again?

You should also be able to open the rent.lock file in RStudio and browse its contents. If a package is missing from that but which was included (such as SHINY) in the call to renv::install I had you run before, then I'm unsure what didn't work. In that case, please review the introductory documentation for renv itself, and then ensure that the lock file reflects the packages that would be loaded without issue when the app is run locally.

If this proves too cumbersome or finicky, we can use the explicit loading approach, rather than the functional one I had us switch to. That is, change the call to "lapply require package in package vector" to multiple lines of "library(package)".

Let me know if you have any luck. If you want to switch to the explicit library loading approach, it will be important that you delete the renv.lock file from your working copy of the code base before trying to deploy again.
